#!/bin/bash

cd $(dirname $0)/..

function copy_assets {
  cp -R ./assets/* ./build/
}

function print_usage {
  echo "Usage:
  build all
  build src|html|tests|docs [docs|html|...]

Options:
  all   - Same as 'build html src tests docs'
  src   - Compile the .coffee files in src
  html  - Concat all pages and insert them into
          the html/index.html template
  tests - Compile the .coffee files in test/tests/src
  docs  - Create the Docco documentation"
  exit 1
}

if [[ $# = 0 ]]; then
  print_usage
fi

while [[ $# > 0 ]]; do # for each argument...
  case "$1" in
    "all" )
      tools/build html src tests docs
      exit $?
      ;;
    
    "html" )
      mkdir -pm 0777 ./build
      
      # Concat the pages, and add a leading tab to each line
      cat ./html/pages/*.html | sed "s/^/	/" 1> ./html/tmp.html
      
      # Insert the result into the template
      placeholder="<!-- body -->"
      sed -e "/$placeholder/r ./html/tmp.html" -e "/$placeholder/d" ./html/index.html 1> ./build/index.html
      
      # Remove the temp file
      rm ./html/tmp.html
      
      # Copy the other files
      cp -R ./css ./build/
      copy_assets
      
      echo "Built html -> build/index.html"
    ;;
    
    "src" )
      # Compile src into several files
      mkdir -pm 0777 ./build/javascript
      coffee -c -o ./compiled ./src/*.coffee || exit 1
      
      # Compile src into a single file, too 
      # coffee -c -j lyt -o ./dist ./src/*.coffee || exit 1
      
      echo "Built src -> build/javascript"
    ;;
    
    "tests" ) 
      mkdir -pm 0777 ./build/test
      
      # Compile the tests into a single file
      coffee -c -j "suite" -o ./build/test/ ./test/src/*.coffee || exit 1
      
      # Copy the other test files
      cp ./test/index.html ./build/test/
      cp -R ./test/fixtures ./build/test/
      
      # Copy the assets, too
      copy_assets
      
      echo "Built tests"
    ;;
    
    "docs" )
      # Run docco on the src files
      docco ./src/*.coffee 1> /dev/null || exit 1
      
      echo "Built docs"
    ;;
    
    * ) # Unrecognized argument
      print_usage
    ;;
  esac
  shift # shift to next argument
done
